/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import activityRender.ActivityRender;
import java.net.MalformedURLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Katherine
 */
public class Pestanas extends javax.swing.JFrame {
    //captura de pantalla
    ActivityRender activityRender;
    boolean perspectivaActivityRender = true;
    public static boolean iPerspectivaActivityRender = false;
    public static boolean dPerspectivaActivityRender = false;
    //captura de audio
    boolean perspectivaAudioRecorder = false;
    public static boolean iPerspectivaAudioRecorder = false;
    public static boolean dPerspectivaAudioRecorder = false;
    //captura con videocam
    boolean perspectivaFaceRecorder = false;
    public static boolean iFaceRecorder = false;
    public static boolean dFaceRecorder = false;
    
    String codigoProyecto = "cod1";
    int cantidadMuestra = 0;
    String path = "C:\\Users\\Katherine\\Documents\\MEMORIA\\MemoriacodigoEbox\\muestras";
    //
    
    
    /**
     * Creates new form Pestanas
     */
    public Pestanas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIniciar = new javax.swing.JLabel();
        btnDetener = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnIniciar.setBackground(new java.awt.Color(102, 255, 51));
        btnIniciar.setText("Iniciar");
        btnIniciar.setOpaque(true);
        btnIniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIniciarMouseClicked(evt);
            }
        });

        btnDetener.setBackground(new java.awt.Color(255, 0, 0));
        btnDetener.setText("Detener");
        btnDetener.setOpaque(true);
        btnDetener.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDetenerMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(btnDetener, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(189, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnDetener, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(btnIniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(82, 82, 82))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarMouseClicked
        // TODO add your handling code here:
        //definir nombre para muestra
        cantidadMuestra = cantidadMuestra +1;
        new Thread(new Runnable(){
        @Override
        public void run(){
            System.out.println("****** Inicio captura de muestras ******");
            
            
            //captura pantalla
        if(perspectivaActivityRender){
                try {
                    activityRender = new ActivityRender();
                    //iniciar perspectiva
                    activityRender.inicializar(path, cantidadMuestra);
                   // activityRender.test();
                } catch (Exception ex) {
                    Logger.getLogger(Pestanas.class.getName()).log(Level.SEVERE, null, ex);
                }
        }
        
        while(perspectivaActivityRender == true && iPerspectivaActivityRender == false ){
            System.out.println("Esperando a iniciar Activity Render");
        }
        //captura webcam y audio
        if(perspectivaFaceRecorder){
        //iniciarPerspectiva
        }
        while(perspectivaFaceRecorder == true && iFaceRecorder == false && iPerspectivaAudioRecorder == false){
            System.out.println("Esperando a iniciar Face Recorder y audio");
        }
        
        
        
        }
        
        }).start();
    }//GEN-LAST:event_btnIniciarMouseClicked

    private void btnDetenerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetenerMouseClicked
        // TODO add your handling code here:
        
           new Thread(new Runnable(){
        @Override
        public void run(){
            System.out.println("****** deteniendo captura de muestras ******");
            
            
            //captura pantalla
        if(perspectivaActivityRender){
                try {
                    activityRender.detener();
                } catch (MalformedURLException ex) {
                    Logger.getLogger(Pestanas.class.getName()).log(Level.SEVERE, null, ex);
                }
        }
        
        while(perspectivaActivityRender == true && dPerspectivaActivityRender == false ){
            System.out.println("Esperando a detener Activity Render");
        }
        //captura webcam y audio
        if(perspectivaFaceRecorder){
        //iniciarPerspectiva
        }
        while(perspectivaFaceRecorder == true && dFaceRecorder == false && iPerspectivaAudioRecorder == false){
            System.out.println("Esperando a detener Face Recorder y audio");
        }
        
        
            System.out.println("Captura detenida");
        }
        
        }).start();
           
    }//GEN-LAST:event_btnDetenerMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pestanas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pestanas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pestanas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pestanas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pestanas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnDetener;
    private javax.swing.JLabel btnIniciar;
    // End of variables declaration//GEN-END:variables
}
