/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package player;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.util.Hashtable;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;
import javax.swing.Timer;


/**
 *
 * @author Katherine
 */
public class TestVideo1 extends javax.swing.JFrame {
public static String store = "FaceRecorderTemporal";
boolean isRunning = false;
public static int captureInterval = 40;
public int time = 0;
public boolean enable = true;
public int i =0;
public boolean primerInicio = true;
public boolean pause = false;
      /**
     * Creates new form TestVideo
     */
    public TestVideo1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        canvas1 = new java.awt.Canvas();
        video = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();
        tagsAutomatico = new javax.swing.JSlider();
        player = new javax.swing.JSlider();
        tagManual = new javax.swing.JSlider();
        btnDetener = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btnPausa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnIniciar.setText("iniciar");
        btnIniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIniciarMouseClicked(evt);
            }
        });
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        tagsAutomatico.setBackground(new java.awt.Color(204, 204, 204));
        tagsAutomatico.setForeground(new java.awt.Color(0, 0, 0));
        tagsAutomatico.setMajorTickSpacing(1);
        tagsAutomatico.setMaximum(12);
        tagsAutomatico.setPaintLabels(true);
        tagsAutomatico.setPaintTicks(true);
        tagsAutomatico.setSnapToTicks(true);
        tagsAutomatico.setValue(0);
        tagsAutomatico.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tagsAutomaticoStateChanged(evt);
            }
        });
        tagsAutomatico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tagsAutomaticoMouseClicked(evt);
            }
        });

        player.setBackground(new java.awt.Color(204, 204, 204));
        player.setForeground(new java.awt.Color(0, 0, 0));
        player.setMajorTickSpacing(1);
        player.setMaximum(12);
        player.setPaintLabels(true);
        player.setPaintTicks(true);
        player.setSnapToTicks(true);
        player.setValue(0);
        player.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                playerStateChanged(evt);
            }
        });
        player.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playerMouseClicked(evt);
            }
        });

        tagManual.setBackground(new java.awt.Color(204, 204, 204));
        tagManual.setForeground(new java.awt.Color(0, 0, 0));
        tagManual.setMajorTickSpacing(1);
        tagManual.setMaximum(12);
        tagManual.setPaintLabels(true);
        tagManual.setPaintTicks(true);
        tagManual.setSnapToTicks(true);
        tagManual.setValue(0);
        tagManual.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tagManualStateChanged(evt);
            }
        });
        tagManual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tagManualMouseClicked(evt);
            }
        });

        btnDetener.setText("detener");

        jButton1.setText("<<");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("<");

        jButton3.setText(">");

        jButton4.setText(">>");

        btnPausa.setText("pausar");
        btnPausa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPausaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jButton1)
                .addGap(49, 49, 49)
                .addComponent(jButton2)
                .addGap(85, 85, 85)
                .addComponent(btnIniciar)
                .addGap(32, 32, 32)
                .addComponent(btnPausa)
                .addGap(29, 29, 29)
                .addComponent(btnDetener)
                .addGap(48, 48, 48)
                .addComponent(jButton3)
                .addGap(55, 55, 55)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(video, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(312, 312, 312)
                        .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(player, javax.swing.GroupLayout.PREFERRED_SIZE, 1316, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tagsAutomatico, javax.swing.GroupLayout.PREFERRED_SIZE, 1316, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tagManual, javax.swing.GroupLayout.PREFERRED_SIZE, 1316, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(video, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)))
                .addComponent(player, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tagsAutomatico, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tagManual, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIniciar)
                    .addComponent(btnDetener)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(btnPausa))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void btnIniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarMouseClicked
        /*Hashtable<Integer, JLabel> labels = new Hashtable<Integer, JLabel>();
	labels.put(0, new JLabel("Lenta"));
	labels.put(5, new JLabel("Media"));
	labels.put(6, new JLabel("Rápida"));
	tagsAutomatico.setLabelTable(labels);*/
        pause = false;
        if(primerInicio){player.setMaximum(11);
        tagsAutomatico.setMaximum(11);
        tagManual.setMaximum(11);
        //primerInicio= false;
        }
        
        if(enable){
            isRunning= true;
        enable = false;
        player.setEnabled(false);
        tagsAutomatico.setEnabled(false);
        tagManual.setEnabled(false);
        
        }
        else
        {
            isRunning= false;
            enable = true;
            player.setEnabled(true);
            tagsAutomatico.setEnabled(true);
            tagManual.setEnabled(true);
        }
        if(primerInicio){new VideoFeedTaker().start();}
        
        final Timer t = new Timer(1000, new ActionListener() {
        public void actionPerformed(ActionEvent e) {
            time=time+1;
            if(time == 12 || pause == true){
            ((Timer) e.getSource()).stop();
          }
            player.setValue(time);
            tagsAutomatico.setValue(time);
            tagManual.setValue(time);
            
            
        
        }
    });
    t.start();
    }//GEN-LAST:event_btnIniciarMouseClicked

    private void tagsAutomaticoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tagsAutomaticoStateChanged
        // TODO add your handling code here:
        System.out.println("valor: "+ tagsAutomatico.getValue());
    }//GEN-LAST:event_tagsAutomaticoStateChanged

    private void tagsAutomaticoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tagsAutomaticoMouseClicked
        // TODO add your handling code here:
        
        if(SwingUtilities.isRightMouseButton(evt)){
            System.out.println("Hice clik con el derecho");
        }
        
    }//GEN-LAST:event_tagsAutomaticoMouseClicked

    private void playerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_playerStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_playerStateChanged

    private void playerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playerMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_playerMouseClicked

    private void tagManualStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tagManualStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_tagManualStateChanged

    private void tagManualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tagManualMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tagManualMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnPausaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPausaMouseClicked
        // TODO add your handling code here:
        
        isRunning= false;
        player.setEnabled(true);
        tagsAutomatico.setEnabled(true);
        tagManual.setEnabled(true);
        pause = true;
        enable=true;
         
    }//GEN-LAST:event_btnPausaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestVideo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestVideo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestVideo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestVideo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestVideo1().setVisible(true);
            }
        });
    }
        class VideoFeedTaker extends Thread{
           @Override
        public void run() {
               System.out.println("Entre al hilo");
               File f = new File(store);
		File[] fileLst = f.listFiles();
                System.out.println("cantidad de imagenes: "+ fileLst.length);
               
                ImageIcon icon;
                while(isRunning){
                                
                   try {
                       //System.out.println("i: "+i);
                     //  System.out.println("path: "+fileLst[i].getAbsolutePath());
                       icon = new ImageIcon(fileLst[i].getAbsolutePath());
                       video.setIcon(icon);
                       if(i==fileLst.length-1){
                       isRunning=false;
                       }
                       i+=1;
                
                   
			// 10 FPS Thread.sleep(100);
			Thread.sleep(captureInterval);
                        
                } catch (InterruptedException ex) {
                    //Logger.getLogger(CameraTest.class.getName()).log(Level.SEVERE, null, ex);
                } 
                
                }
      
        }
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetener;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnPausa;
    private java.awt.Canvas canvas1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JSlider player;
    private javax.swing.JSlider tagManual;
    private javax.swing.JSlider tagsAutomatico;
    private javax.swing.JLabel video;
    // End of variables declaration//GEN-END:variables
}
