/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package player;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.util.Hashtable;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;
import javax.swing.Timer;


/**
 *
 * @author Katherine
 */
public class TestVideo1 extends javax.swing.JFrame {
//path de las perspectivas    
public static String store = "FaceRecorderTemporal";
//variable que permite detener o iniciar la reproducción de las perspectivas
boolean isRunning = false;
//FPS
public static int captureInterval = 40;
public static int fPS = 25;

public int tiempoVideoTranscurrido = 0;
//variable que permite habilitar o deshabilitar el jslider
public boolean enable = true;
//frames que han sido mostrados
public int frameSegundo =0;
//variable que permite setear los valores iniciales
public boolean primerInicio = true;
//variable que permite detener el video
public boolean detener = false;
//tiempo de duración de la muestra
public int tiempoDuracionMuestra = 12;

public int contadorFrameSegundo;

public File f;   
public File[] fileLst;
public ImageIcon icon; 

//frame x segundo
public Hashtable<Integer, Integer> FPS = new Hashtable<Integer, Integer>();

//tags
public Hashtable<Integer, JLabel> tag = new Hashtable<Integer, JLabel>();

public int posTagManual;
      /**
     * Creates new form TestVideo
     */
    public TestVideo1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        canvas1 = new java.awt.Canvas();
        video = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();
        tagsAutomatico = new javax.swing.JSlider();
        player = new javax.swing.JSlider();
        tagManual = new javax.swing.JSlider();
        btnDetener = new javax.swing.JButton();
        retrocederSegundo = new javax.swing.JButton();
        avanzarSegundo = new javax.swing.JButton();
        btnPausa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnIniciar.setText("iniciar");
        btnIniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIniciarMouseClicked(evt);
            }
        });
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        tagsAutomatico.setBackground(new java.awt.Color(204, 204, 204));
        tagsAutomatico.setForeground(new java.awt.Color(0, 0, 0));
        tagsAutomatico.setMajorTickSpacing(1);
        tagsAutomatico.setMaximum(12);
        tagsAutomatico.setPaintLabels(true);
        tagsAutomatico.setPaintTicks(true);
        tagsAutomatico.setSnapToTicks(true);
        tagsAutomatico.setValue(0);
        tagsAutomatico.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tagsAutomaticoStateChanged(evt);
            }
        });
        tagsAutomatico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tagsAutomaticoMouseClicked(evt);
            }
        });

        player.setBackground(new java.awt.Color(204, 204, 204));
        player.setForeground(new java.awt.Color(0, 0, 0));
        player.setMajorTickSpacing(1);
        player.setMaximum(12);
        player.setPaintLabels(true);
        player.setPaintTicks(true);
        player.setSnapToTicks(true);
        player.setValue(0);
        player.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                playerStateChanged(evt);
            }
        });
        player.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playerMouseClicked(evt);
            }
        });

        tagManual.setBackground(new java.awt.Color(204, 204, 204));
        tagManual.setForeground(new java.awt.Color(0, 0, 0));
        tagManual.setMajorTickSpacing(1);
        tagManual.setMaximum(12);
        tagManual.setPaintLabels(true);
        tagManual.setPaintTicks(true);
        tagManual.setSnapToTicks(true);
        tagManual.setValue(0);
        tagManual.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tagManualStateChanged(evt);
            }
        });
        tagManual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tagManualMouseClicked(evt);
            }
        });

        btnDetener.setText("detener");
        btnDetener.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDetenerMouseClicked(evt);
            }
        });

        retrocederSegundo.setText("<");

        avanzarSegundo.setText(">");

        btnPausa.setText("pausar");
        btnPausa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPausaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(retrocederSegundo)
                .addGap(85, 85, 85)
                .addComponent(btnIniciar)
                .addGap(32, 32, 32)
                .addComponent(btnPausa)
                .addGap(29, 29, 29)
                .addComponent(btnDetener)
                .addGap(48, 48, 48)
                .addComponent(avanzarSegundo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(video, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(312, 312, 312)
                        .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(player, javax.swing.GroupLayout.PREFERRED_SIZE, 1316, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tagsAutomatico, javax.swing.GroupLayout.PREFERRED_SIZE, 1316, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tagManual, javax.swing.GroupLayout.PREFERRED_SIZE, 1316, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(video, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)))
                .addComponent(player, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tagsAutomatico, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tagManual, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIniciar)
                    .addComponent(btnDetener)
                    .addComponent(retrocederSegundo)
                    .addComponent(avanzarSegundo)
                    .addComponent(btnPausa))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void btnIniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarMouseClicked
        /*Hashtable<Integer, JLabel> labels = new Hashtable<Integer, JLabel>();
	labels.put(0, new JLabel("Lenta"));
	labels.put(5, new JLabel("Media"));
	labels.put(6, new JLabel("Rápida"));
	tagsAutomatico.setLabelTable(labels);*/
        
        detener = false;
        //Se determina si es el primer inicio para determinar el largo y la división de las lineas de tiempoDuracionMuestra
        if(primerInicio){
            
            player.setMaximum(tiempoDuracionMuestra);
            tagsAutomatico.setMaximum(tiempoDuracionMuestra);
            tagManual.setMaximum(tiempoDuracionMuestra);
            primerInicio= false;
        
        }
        
        if(enable){
            
            isRunning= true;
            enable = false;
            player.setEnabled(false);
            tagsAutomatico.setEnabled(false);
            tagManual.setEnabled(false);
        
        }
        else
        {
            isRunning= false;
            enable = true;
            player.setEnabled(true);
            tagsAutomatico.setEnabled(true);
            tagManual.setEnabled(true);
        }
        ///SE INICIA LA REPRODUCCIÓN DE MUESTRAS
        new VideoFeedTaker().start();
        ///1000-> 1 acción cada 1 segundo
        final Timer t = new Timer(1000, new ActionListener() {
        public void actionPerformed(ActionEvent e) {
            
            if(tiempoVideoTranscurrido == tiempoDuracionMuestra || detener == true){
                    //se detiene linea de tiempo
                    ((Timer) e.getSource()).stop();
          } else{
                tiempoVideoTranscurrido=tiempoVideoTranscurrido+1;
                player.setValue(tiempoVideoTranscurrido);
                tagsAutomatico.setValue(tiempoVideoTranscurrido);
                tagManual.setValue(tiempoVideoTranscurrido);
                FPS.put(tiempoVideoTranscurrido, frameSegundo);
                
                System.out.println("Al segundo: "+ tiempoVideoTranscurrido + " han pasado "+ frameSegundo+ " frames");
            }
            
            }
    });
    t.start();
    }//GEN-LAST:event_btnIniciarMouseClicked

    private void tagsAutomaticoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tagsAutomaticoStateChanged
        //CAPTURA   LINEA DE TIEMPO AUTOMATICA
        if(detener){
            System.out.println("[Linea automatica] valor: "+ tagsAutomatico.getValue());
            System.out.println("frame: "+FPS.get(tiempoVideoTranscurrido));
            //asignar valores
            tiempoVideoTranscurrido =  tagsAutomatico.getValue();
            frameSegundo = tiempoVideoTranscurrido * fPS;
            
        }
        
        
    }//GEN-LAST:event_tagsAutomaticoStateChanged

    private void tagsAutomaticoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tagsAutomaticoMouseClicked
        // TODO add your handling code here:
        
        if(SwingUtilities.isRightMouseButton(evt)){
            System.out.println("Hice clik con el derecho");
        }
        
    }//GEN-LAST:event_tagsAutomaticoMouseClicked

    private void playerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_playerStateChanged
            //CAPTURA   LINEA DE TIEMPO 
       if(detener){ System.out.println("[Linea tiempo] valor: "+ player.getValue());}
        
    }//GEN-LAST:event_playerStateChanged

    private void playerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playerMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_playerMouseClicked

    private void tagManualStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tagManualStateChanged
        //CAPTURA   LINEA DE TIEMPO MANUAL
   
        if(detener)
        {System.out.println("[Linea manual] valor: "+ tagManual.getValue());
        posTagManual = tagManual.getValue();
        
        }
    }//GEN-LAST:event_tagManualStateChanged

    private void tagManualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tagManualMouseClicked
        // TAG MANUAL
       for (int i = 0; i < tiempoDuracionMuestra; i++) {
            if(i!=posTagManual){
            tag.put(i,  new JLabel(String.valueOf(i)));
            
            }
            
        }
       if(detener){
        if(SwingUtilities.isRightMouseButton(evt)){
        
                tag.put(posTagManual,  new JLabel("Tag"));
	        System.out.println("Hice clik con el derecho");
                tagManual.setLabelTable(tag);
        }
       
       }
        
        
        
    }//GEN-LAST:event_tagManualMouseClicked

    private void btnPausaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPausaMouseClicked
        //PAUSA
        
        //detener proyección de frames
        isRunning= false;
        //habilitar lineas de tiempo
        player.setEnabled(true);
        tagsAutomatico.setEnabled(true);
        tagManual.setEnabled(true);
        //detener avance linea de tiempo
        detener = true;
        
        enable=true;
         
    }//GEN-LAST:event_btnPausaMouseClicked

    private void btnDetenerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetenerMouseClicked
          //DETENER
          //detener
          //detener proyección de frames
        isRunning= false;
        //habilitar lineas de tiempo
        player.setEnabled(true);
        tagsAutomatico.setEnabled(true);
        tagManual.setEnabled(true);
        //detener avance linea de tiempo
        detener = true;
        
        enable=true;
        
        //reiniciar valores
        tiempoVideoTranscurrido = 0;
        frameSegundo = 0;
        player.setValue(tiempoVideoTranscurrido);
        tagsAutomatico.setValue(tiempoVideoTranscurrido);
        tagManual.setValue(tiempoVideoTranscurrido);
        icon = new ImageIcon(fileLst[frameSegundo].getAbsolutePath());
        video.setIcon(icon);
        
    }//GEN-LAST:event_btnDetenerMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestVideo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestVideo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestVideo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestVideo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestVideo1().setVisible(true);
            }
        });
    }
        class VideoFeedTaker extends Thread{
           @Override
        public void run() {
            System.out.println("Entre al hilo");
            f = new File(store);
            fileLst = f.listFiles();
            
            System.out.println("cantidad de imagenes: "+ fileLst.length);
            while(isRunning){
                                
                   try {
                       //System.out.println("frameSegundo: "+frameSegundo);
                     //  System.out.println("path: "+fileLst[frameSegundo].getAbsolutePath());
                       icon = new ImageIcon(fileLst[frameSegundo].getAbsolutePath());
                       video.setIcon(icon);
                       if(frameSegundo==fileLst.length-1){
                       isRunning=false;
                       //detener = true;
                       }
                       frameSegundo+=1;
                
                   
			// 10 FPS Thread.sleep(100);
			Thread.sleep(captureInterval);
                        
                } catch (InterruptedException ex) {
                    //Logger.getLogger(CameraTest.class.getName()).log(Level.SEVERE, null, ex);
                } 
                
                }
      
        }
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton avanzarSegundo;
    private javax.swing.JButton btnDetener;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnPausa;
    private java.awt.Canvas canvas1;
    private javax.swing.JSlider player;
    private javax.swing.JButton retrocederSegundo;
    private javax.swing.JSlider tagManual;
    private javax.swing.JSlider tagsAutomatico;
    private javax.swing.JLabel video;
    // End of variables declaration//GEN-END:variables
}
